### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gingeralesy** [Shinmera/vpetjam#1]
**Genetics**
- [ ] Mutations. There needs to be a chart on how different parent combinations may mutate the result.
- [x] Averages. Numerical values should be able to get their average value as the result. This is the case for Speed and Hue.
- [x] Maybe not store every mutation? Currently every single possible gene version gets stored in a hash table. Might be better just to have the base defaults in there. This also means that the gene might be unique to the creature, making its ID value irrelevant. Allow NIL ID's to convey this?

**Comment by gingeralesy** [comment]
**Genetics Continued**
- [ ] Determinism. The only randomness should be in the bought seeds. Which seed you buy determines which gene is randomised for the product. So make all cross-breeding deterministic, the only randomness is which parent's gene is inherited.
- How do the farming Zones affect this?

**Comment by gingeralesy** [comment]
**Genetics of Wealth**
- [x] Pricing. The pricing depends entirely on how the game is routed and how long it should take. This is design work I don't think I can do myself, but the code is there and ready.
- What else needs doing?

**Comment by gingeralesy** [comment]
As a note, changes from the first post in this thread included changing genes from objects of their own to numerical values held in a hash table. Everything holds every type of gene. If we're to add any special ones, such as traits that the genetical creature can actively use, or return recessive genes back, they'd need to be done differently, probably as function parameter.s
